meta_product_name: "Sparks <3"
meta_title: "Sparks <3 - Regular, amazing date nights for couples made easy"
meta_description: "Sparks makes date nights for couples easy! We provide you with personalised date night recommendations (free of charge!), so you can go on regular, amazing date nights with your partner in New York City!"
meta_image: "cover.jpg" # should exist in `app/assets/images/`
meta_type: "website"
meta_url: "https://www.sparks-app.com"
